on: [push, pull_request]

name: Continuous integration

env:
  MSRV: 1.65.0
  CARGO_INCREMENTAL: 0 # set here rather than on CI profile so that the tests get it too

jobs:
  skip_duplicate_jobs:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
  check-msrv:
    needs: skip_duplicate_jobs
    if: ${{ needs.skip_duplicate_jobs.outputs.should_skip != 'true' }}
    name: Check (MSRV)
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            deps: sudo apt-get update && sudo apt-get install libusb-1.0-0-dev libftdi1-dev libudev-dev qemu-system-misc
         #- os: windows-latest
         #  deps: vcpkg install libusb libftdi1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        run: '${{ matrix.deps }}'
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.MSRV }}
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Install cargo-readme
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-readme
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --profile=ci
  check:
    needs: skip_duplicate_jobs
    if: ${{ needs.skip_duplicate_jobs.outputs.should_skip != 'true' }}
    name: Check
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            deps: sudo apt-get update && sudo apt-get install libusb-1.0-0-dev libftdi1-dev libudev-dev
         #- os: windows-latest
         #  deps: vcpkg install libusb libftdi1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        run: '${{ matrix.deps }}'
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Install cargo-readme
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-readme
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --profile=ci
  test:
    needs: skip_duplicate_jobs
    if: ${{ needs.skip_duplicate_jobs.outputs.should_skip != 'true' }}
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            deps: sudo apt-get update && sudo apt-get install libusb-1.0-0-dev libftdi1-dev libudev-dev
         #- os: windows-latest
         #  deps: vcpkg install libusb libftdi1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        run: '${{ matrix.deps }}'
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.MSRV }}
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Install cargo-readme
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-readme
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --profile=ci
  clippy:
    needs: skip_duplicate_jobs
    if: ${{ needs.skip_duplicate_jobs.outputs.should_skip != 'true' }}
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install libusb-1.0-0-dev libftdi1-dev libudev-dev
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.MSRV }}
          override: true
          components: clippy
      - uses: Swatinem/rust-cache@v1
      - name: Install cargo-readme
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-readme
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --profile=ci -- -D warnings
